# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d104cf673a970d2908576e85c5f0b05486639dda61e4634ee9e9f3309ce5f429c514ce24871ba7337df1d919f6fae4a3d6326d8b9dbabae7f6bb1e0341b1e6

test:
  secret_key_base: 01f4153065ebc8c1f729a96dc8dc58a6bf210e497358b90f1f76c31a9eb86f53e73c10f8d99c92926e336420be5420e9c92a9c7548355ea30b76e73afa2f1fee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
